language: rust
sudo: false

os:
- osx
- linux

rust:
- stable
- beta
- nightly

before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
- travis-cargo build --verbose
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    p=$(cd ./target/debug/build/onig_sys-*/out/lib/ && pwd)
    echo "adding $p to linker path"
    export LD_LIBRARY_PATH="${p}:${LD_LIBRARY_PATH}"
  fi
- travis-cargo test --verbose
- travis-cargo --only stable doc

after_success:
- travis-cargo --only stable doc-upload
