language: rust
sudo: false

os:
- osx
- linux

rust:
- stable
- beta
- nightly

before_script:
- pip install 'travis-cargo<0.2' --user
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    export PATH=$HOME/.local/bin:$PATH
  else
    export PATH=$HOME/Library/Python/$VERSION/bin
  fi

script:
- travis-cargo build
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    p=$(cd ./target/debug/build/onig_sys-*/out/lib/ && pwd)
    echo "adding $p to linker path"
    export LD_LIBRARY_PATH="${p}:${LD_LIBRARY_PATH}"
  fi
- travis-cargo test
- travis-cargo --only stable doc

after_success:
- travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
