[package]
name = "onig"
version = "0.3.0"
authors = ["Will Speak <will@willspeak.me>"]

description = """Rust-Onig is a set of rust bindings for the
            oniguruma regular expression library."""
repository = "http://github.com/iwillspeak/rust-onig"
readme = "README.md"
license = "MIT"

[dependencies]
libc = "0.1"
bitflags = "0.3"
lazy_static = "0.1"

[dependencies.onig_sys]
version = "0.2"
path = "onig_sys"
